### ISSUE TITLE
Support for Thunderbird 68?

### ISSUE THREAD

**Issue by d4k0** [SecUSo/torpedo#5]
Thunderbird 68 was released yesterday and requires changes to add-ons. Will you update the add-on to make it compatible with Thunderbird 68?

**Comment by beerisgood** [comment]
*push*

**Comment by ghost** [comment]
Hello, I modified the extension so it is working with Thunderbird 68.

The addon now needs a manifest.json file instead of the old install.rdf file to work.
You have to create a new manifest.json file with the following content:

```
{
"manifest_version": 2,
"name": "TORPEDO - TOoltip-poweRed Phishing Email DetectiOn",
"description": "TORPEDO is a tool for recognizing untrustworthy links (phishing). Move the mouse pointer over a link in your email. TORPEDO displays the correct web address in a tooltip and helps you to analyze it. Trustworthy links are displayed in a green box. Links you opened at least two times are displayed in an orange box.",
"version": "2.3.2",
"author": "TU Darmstadt SECUSO",
"homepage_url": "https://secuso.aifb.kit.edu/TORPEDO.php",
"applications": {
"gecko": {
"id": "torpedo@tu-darmstadt.de",
"strict_min_version": "68.0"
}
},
"icons": {
"32": "torpedo/skin/icon32.png"
},
"legacy": {
"type": "xul",
"options": {
"page": "chrome://torpedo/content/options.xul",
"open_in_tab": true
}
}
}
```
Copy/move the manifest.json file to the root directory of .xpi addon.

The 64 pixel icon is to big and did not show up in the extension. So I resized it to a 32 pixel icon.
You have to store the resized icon in the \chrome\skin\ directory and name it icon32.png.
Just add the modified files to the .xpi addon with a zip archiver. .xpi addons are compressed with zip format.

Now the extension can be installed in Thunderbird 68.x and above without error. The extension is working so far and I haven't an issue yet. 
But maybe the Devs could have a look at it too, if these modifications are sufficiently.

**Comment by beerisgood** [comment]
Thanks @protvis74 that works.
Sadly the menu have some bugs. If i go to "Domains" and click on "show entrys" from Dev, the list is empty

**Comment by petermayer** [comment]
We are currently updating TORPEDO to work on the newest version of Thunderbird. However, there are also some under the hood changes in Thunderbird which render this non-trivial. Please bear with us until the add-on is updated.

**Comment by d4k0** [comment]
@petermayer 
Thanks for the info!

**Comment by ghost** [comment]
Does not even install with 71.0b1 (64-bit)

**Comment by d4k0** [comment]
Works in Thunderbird 68.x, so this issue can be closed.
