### ISSUE TITLE
Support for Thunderbird 78?

### ISSUE THREAD

**Issue by d4k0** [SecUSo/torpedo#9]
Thunderbird 78 was released this week which only allows to install WebExtensions/MailExtensions. Are there plans to update this extension for Thunderbird 78?

**Comment by lauraimler** [comment]
Unfortunately, we are currently unable to offer a solution for TB 78 for various reasons.
In the meantime, we can only offer our version for various web mailers, which will continue to work:

https://chrome.google.com/webstore/detail/torpedo-browser/cjglnlkhmaffelpeagnmgimhjhdpjomi?hl=de
https://addons.mozilla.org/de/firefox/addon/torpedo-browser/

**Comment by philheller** [comment]
We are aware of the situation and are currently working towards the next major version (3.0.0) for TORPEDO.
It will be released in the near future.

**Comment by philheller** [comment]
We have been working on a solution and have just released a newest version in the main branch.
This new release contains a few bigger structural changes due to fundamental changes under the hood of Thunderbird.
Note, that the newest version is fully compatible with the beta of Thunderbird (*version 87.0b3*)!

**Comment by d4k0** [comment]
I just tried the latest version of the main branch with Thunderbird 78.10.2 and it seems to be working quite well. Thanks for the effort!
